# Generated by Django 3.0.7 on 2020-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('cron', models.CharField(max_length=45)),
                ('condition', models.CharField(max_length=255)),
                ('template_mail', models.TextField()),
                ('last_run', models.DateTimeField(verbose_name='last_run_timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='MailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fron', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('cc', models.CharField(max_length=255)),
            ],
        ),
    ]
