# Generated by Django 3.0.7 on 2020-06-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailData',
            new_name='MailMetadata',
        ),
    ]
