# Generated by Django 3.0.7 on 2020-06-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200615_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailactions',
            name='condition',
        ),
    ]
