# Generated by Django 3.0.7 on 2020-06-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mailactions_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmetadata',
            name='subject',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
