# Generated by Django 3.0.7 on 2020-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mailmetadata_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmetadata',
            name='cc',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailmetadata',
            name='fron',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailmetadata',
            name='to',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
