# Generated by Django 3.0.7 on 2020-06-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200619_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_username', models.CharField(default='None', max_length=255)),
                ('acc_password', models.CharField(default='None', max_length=255)),
                ('smtp_address', models.CharField(default='None', max_length=255)),
                ('smtp_port', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mailmetadata',
            name='id_mail_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.MailActions'),
            preserve_default=False,
        ),
    ]
