# Generated by Django 3.0.7 on 2020-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200622_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailactions',
            name='is_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
