# Generated by Django 3.0.7 on 2020-06-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mailactions_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmetadata',
            name='id_mail_action',
        ),
        migrations.AddField(
            model_name='mailactions',
            name='mail_metadata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.MailMetadata'),
            preserve_default=False,
        ),
    ]
