# Generated by Django 3.0.7 on 2020-06-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200624_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailactions',
            name='mail_metadata',
        ),
    ]
