# Generated by Django 3.0.7 on 2020-06-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mailactions_mail_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailactions',
            name='mail_metadata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.MailMetadata'),
            preserve_default=False,
        ),
    ]
