# Generated by Django 3.0.7 on 2020-06-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mailactions_mail_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailactions',
            name='mail_metadata',
        ),
        migrations.DeleteModel(
            name='MailServer',
        ),
        migrations.DeleteModel(
            name='MailActions',
        ),
        migrations.DeleteModel(
            name='MailMetadata',
        ),
    ]
