# Generated by Django 3.0.7 on 2020-06-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_auto_20200624_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='None', max_length=255)),
                ('fron', models.CharField(default='None', max_length=255)),
                ('to', models.CharField(default='None', max_length=255)),
                ('cc', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_username', models.CharField(default='None', max_length=255)),
                ('acc_password', models.CharField(default='None', max_length=255)),
                ('smtp_address', models.CharField(default='None', max_length=255)),
                ('smtp_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MailActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('cron', models.CharField(max_length=45)),
                ('template_mail', models.TextField()),
                ('last_run', models.DateTimeField(verbose_name='last_run_timestamp')),
                ('is_enabled', models.BooleanField()),
                ('mail_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MailMetadata')),
            ],
        ),
    ]
